### PR TITLE
Fix UnicodeDecodeError with some UTF-16

### LINKED ISSUE #447: Bad behaviour of UTF-16 decoding
Hi,

I ran into problems when decoding some `UTF-16` encoded strings, and I'm curious about the way [strings are decoded in the package](https://github.com/ibmdb/python-ibmdb/blob/78993f2e941383c2d9187bf0a626bb0fce3b0892/IBM_DB/ibm_db/ibm_db.c#L1417-L1439), especially in `getSQLWCharAsPyUnicodeObject`.

From my understanding, there is no `BOM` support in the above function. According to [Python documentation](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_DecodeUTF16):
_"If *byteorder is zero, and the first two bytes of the input data are a byte order mark (BOM),
the decoder switches to this byte order and the BOM is not copied into the resulting Unicode string.
If *byteorder is -1 or 1, any byte order mark is copied to the output (where it will result in either a \ufeff or a \ufffe character)."_

Looking at the function definition in `CPython` [code](https://github.com/python/cpython/blob/master/Objects/unicodeobject.c#L5787), it seems that any eventual `BOM` is simply ignored if `*byteorder` is not zero.

According to [getSQLWCharAsPyUnicodeObject at line 1431](https://github.com/ibmdb/python-ibmdb/blob/78993f2e941383c2d9187bf0a626bb0fce3b0892/IBM_DB/ibm_db/ibm_db.c#L1431), the `byteorder` is set depending on the user's machine.

In my case, I have to decode big endian-encoded strings on a little endian machine, so it fails.

The database server is either big or little endian, so in my opinion the information of byteorder to -1 or 1 for decoding should come from it, and not from the macro `is_bigendian`.

Clause D98 of conformance (section 3.10) of the Unicode standard states, _"The UTF-16 encoding scheme may or may not begin with a BOM. However, when there is no BOM, and in the absence of a higher-level protocol, the byte order of the UTF-16 encoding scheme is big-endian."_.

As a quick dirty workaround for my usecase and maximum tolerance, I'd write something like
```C
u = PyUnicode_DecodeUTF16((char *)sqlwcharData, sqlwcharBytesLen, "strict", NULL);
if (PyErr_Occurred()){
    if (PyErr_ExceptionMatches(PyExc_UnicodeDecodeError)){
        PyErr_Clear();
        int bo = 1;
        u = PyUnicode_DecodeUTF16((char *)sqlwcharData, sqlwcharBytesLen, "strict", &bo);
    }
}
return u;
```

In this case, if *bo is `NULL`, CPython will check for a BOM, or convert it as little endian otherwise. In case of failure, we try as bigendian. This way it's working either for strings with or without BOM, `UTF-16-LE` or `UTF-16-BE`.

Any help appreciated !

### LINKED ISSUE #476: ascii codec error if column name contains Ñ
> I was able to reproduce this. This seems to be a bug in QSQCLI handling of statement text coming in as UTF-8. It converts the text from UTF-8 to job CCSID, but uses the UTF-8 length instead of the converted length since it assumes a one-to-one byte mapping, which is not always the case with UTF-8.
> 
> You can work around this by padding the end with blanks for each extra byte of UTF-8 data.
> 
> ```python
> import os
> import subprocess
> import ibm_db_dbi
> 
> # Set job to CCSID 284 (Spanish)
> proc = subprocess.run(['getjobid', '-s', str(os.getpid())], stdout=subprocess.PIPE)   
> jobname = proc.stdout.decode().rstrip()
> proc = subprocess.run(['system', 'CHGJOB {} CCSID(284)'.format(jobname)], stdout=subprocess.PIPE)
> 
> 
> conn = ibm_db_dbi.connect()
> cur = conn.cursor()
> cur.execute('create table birthday(aÑo decimal(4,0))    ')
> 
> query = 'select aÑo from birthday'
> try:
>     cur.execute(query)
>     print('"{}" succeeded'.format(query))
> except ibm_db_dbi.ProgrammingError as e:
>     print('"{}" failed'.format(query))
>     print(e)
> 
> try:
>     query = query + ' '
>     cur.execute(query)
>     print('"{}" succeeded'.format(query))
> except ibm_db_dbi.ProgrammingError as e:
>     print('"{}" failed'.format(query))
>     print(e)
> ```
> 
> This gives me:
> 
> ```
> "select aÑo from birthday" failed
> ibm_db_dbi::ProgrammingError: BIRTHDA in KADLER type *FILE not found. SQLSTATE=42704 SQLCODE=-204
> "select aÑo from birthday " succeeded
> ```

How can I change the CCSID???

I try your code:

```
# Set job to CCSID 284 (Spanish)
proc = subprocess.run(['getjobid', '-s', str(os.getpid())], stdout=subprocess.PIPE)   
jobname = proc.stdout.decode().rstrip()
proc = subprocess.run(['system', 'CHGJOB {} CCSID(284)'.format(jobname)], stdout=subprocess.PIPE)
```

but I get error in first line:

FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

I'm trying in Anaconda enviroment in Windows.

Regards.

_Originally posted by @carlos-merida in https://github.com/ibmdb/python-ibmdb/issues/439#issuecomment-590585728_

### PR DESCRIPTION
**Pull request by theophilechevalier**
Closes #447 
Closes #476 

See #447 for details.

### CODE REVIEW

**Comment by SabaKauser** [comment]
can you please sign as:
DCO 1.1 Signed-off-by: Random J Developer <random@developer.org>

**Comment by theophilechevalier** [comment]
DCO 1.1 Signed-off-by: Théophile Chevalier theophile.chevalier@lenstra.fr

**Comment by kadler** [comment]
> can you please sign as:
> DCO 1.1 Signed-off-by: Random J Developer [random@developer.org](mailto:random@developer.org)

FYI you can enable [dco bot](https://github.com/probot/dco) to do these reminders/checks for you. Solid quality of life improvement.

**Comment by SabaKauser** [comment]
@theophilechevalier , any reason why you closed this?

**Comment by SabaKauser** [comment]
@theophilechevalier , the cpython PyUnicode_DecodeUTF16Stateful(..) decides on encoding depending on the current platform endianess in absence of BOM.
default is bo =0(when passed as NULL)
```c
 if (bo == 0 && size >= 2) {
        const Py_UCS4 bom = (q[1] << 8) | q[0];
        if (bom == 0xFEFF) {
            q += 2;
            bo = -1;
        }
        else if (bom == 0xFFFE) {
            q += 2;
            bo = 1;
        }
        if (byteorder)
            *byteorder = bo;
    }
```

at here, if no BOM in string, then bo=0 holds good.
```c
.
.
#if PY_LITTLE_ENDIAN
    native_ordering = bo <= 0;
    encoding = bo <= 0 ? "utf-16-le" : "utf-16-be";
#else
    native_ordering = bo >= 0;
    encoding = bo >= 0 ? "utf-16-be" : "utf-16-le";
#endif
```

 I am unable to relate your comment with code:
>>>If *bo == NULL, CPython will check for a BOM, or convert it as littleendian
    otherwise. In case of failure, we try as bigendian.

Where is the information that its LE by default or alternately, if server is LE and client is BE, do we not still have the problem?

**Pull request closed without merging**
