### PR TITLE
Pin setuptools during builds.

### LINKED ISSUE #655: pip install ibm_db with error in ibm_db setup command: use_2to3 is invalid.
Python 3.9.6
ibm_db 3.0.4
pip 21.2.4
setuptools 58.0.4

Problem from pip install ibm_db.

**Workaround:** setuptools==56.0.0

ERROR:
<pre>
    Running setup.py install for ibm-db: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cn2swwqk/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/ibm-db
         cwd: /tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/
    Complete output (5 lines):
    Detected 64-bit Python
    /tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py:304: UserWarning: Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the ibm_db module install
    
      warnings.warn(notifyString)
    error in ibm_db setup command: use_2to3 is invalid.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cn2swwqk/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/ibm-db Check the logs for full command output.
</pre>

### PR DESCRIPTION
**Pull request by jaraco**
Fixes #655

### CODE REVIEW

**Comment by amukherjee28** [comment]
Merging the new file in order to address the issue.

**Comment by jaraco** [comment]
With this change, I was able to use `build` to build sdist and wheels of this project on Python 3.10 on macOS.

I recommend to apply this as a bugfix to the latest stable release and cut a new release. I also recommend considering to release wheels, at least for the major platforms, to further limit the impact of the removal of `use_2to3`.

Thereafter, I recommend to port the Python code to a single codebase, either by dropping support for Python 2 or by converting the code to Python 3 and then restoring support for Python 2. I can help with this change too, but I recommend to tackle that later and to release this ASAP to unblock builds.

**Comment by jaraco** [comment]
Thanks @amukherjee28 . Please also take a look at c03508d. It occurred to me that adding a file is a two-step operation if MANIFEST.in is used.

**Comment by amukherjee28** [comment]
Hi @jaraco 

I tried adding the include in MANIFEST.in file like you have suggested but still installation continue to fail with the same error for setuptools version setuptools 58.0.4.

Could you please help me out here.

Thanks

**Comment by jaraco** [comment]
The changes here should work as long as they're installed using pip 10 or later. For building the sdist, they also require building with Setuptools 43 or later (or adding the commit that adds pyproject.toml to MANIFEST.in).

**Pull request merged**
