### PR TITLE
Changes to operations and SchemaEditor 

### PR DESCRIPTION
**Pull request by nhardman**
Please review these changes. They fixed the problems I was seeing and allow me to get django 1.8 running with the latest ibm_db_django

### CODE REVIEW

**Comment by nhardman** [comment]
Hi Saba, I just noticed the changes from another user (hemlatabhatt). They look better than mine, so I'm happy! 

Is the test suite available, I don't recall seeing the tests on GitHub?

**Comment by drpoggi** [comment]
I believe they're referring to the tests django/django provides for various database backends, more info here: https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/#testing-other-python-versions-and-database-backends

**Comment by nhardman** [comment]
Excellent, thanks David.

**Comment by SabaKauser** [comment]
already fixed.

**Pull request closed without merging**
