### PR TITLE
fixed typo in error message

### PR DESCRIPTION
**Pull request by data-henrik**
DCO 1.1 Signed-off-by: Henrik Loeser, hloeser@de.ibm.com

### CODE REVIEW

**Comment by SabaKauser** [comment]
Please sign-off as:
DCO 1.1 Signed-off-by: YOURNAME EMAILID

**Comment by data-henrik** [comment]
@SabaKauser is that a comment for me?

**Comment by kadler** [comment]
@data-henrik yes, see [contributing](https://github.com/ibmdb/python-ibmdb#contributing-to-the-ibm_db-python-project)

Please edit the PR comment and add the DCO sign off string to it. For something this trivial it's *probably* not necessary, but it's easy to do and keeps lawyers appeased.

**Comment by SabaKauser** [comment]
Thanks @data-henrik .
Merged.

**Pull request merged**
