### PR TITLE
Update setup.py file

### PR DESCRIPTION
**Pull request by kparihar7**
I am proposing to update setup.py file to dynamically read DB2 include dataset ($IBM_DB_HOME.SDSNC.H) from the environment variable.
Hardcoding this dataset in setup.py file creates problem for the application having custom dataset names.

### CODE REVIEW

**Comment by amukherjee28** [comment]
I guess this is a standard set for using the naming convention.
https://www.ibm.com/support/knowledgecenter/en/SSEPEK_10.0.0/inst/src/tpc/db2z_whatyouproduce.html

And hence this is kept hidden from user and the setup is done automatically.

introducing a new environment variable will create additional task for education the already existing users.


I would appreciate your feedback on the same.

**Comment by AWADHAMBIKA** [comment]
@kparihar7 
Can you please provide your feedback on above?

**Comment by kparihar7** [comment]
This is a required dataset for installing ibm_db package and have seen Applications are having same dataset defined with different names. Making this dataset name hardcoded in setup.py file throws error while installing it.
So, it will be good if we get this dataset name from the environment file dynamically same like how we are doing for STEPLIB datasets.

**Comment by AWADHAMBIKA** [comment]
thanks @kparihar7. 
But in order to maintain the integrity of package for existing users who did not face this issue and will continue to use it as is, can we change the code in the following way to accommodate your suggestion as well?
```
if (('DB2_INC' not in os.environ)):
	dataset_include = "//'%s.SDSNC.H'" % ibm_db_home
else:
	dataset_include = "//'%s'" % os.environ['DB2_INC']
```

**Comment by AWADHAMBIKA** [comment]
Hi @kparihar7 
Also, there is another library named "SDSNMACS" used in setup.py i.e. 
`subprocess.run(['tso', "oput '{}.SDSNMACS(DSNAO64C)' '{}'".format(ibm_db_home, os.path.join(os.getcwd(), library_x))])`

so that means your suggestion of hardcoding is applicable here as well?
We need to handle this as well?

Please comment.

**Comment by kparihar7** [comment]
@AWADHAMBIKA For the existing user, who have already installed this should not get any issue as this is in installation only and later if any update comes to this package then they can always update their package with this new instruction. 
Adding this logic may create confusion for the users having standard library dataset name.

**Comment by kparihar7** [comment]
@AWADHAMBIKA We should handle this dataset also same like others, so that there will not be any hardcoding in setup.py file and whatever is required can be passed through environment file.
The mentioned datasets will always be in same HLQ but every organization will have the different HLQ and this is already handled with the variable IBM_DB_HOME which makes the complete dataset name.
Ex.- $IBM_DB_HOME.SDSNEXIT
Also,  organization can have the different name for the last qualifier, that is what we want to handle through environment file.

**Comment by AWADHAMBIKA** [comment]
@kparihar7 Sorry I couldn't quite get your point.
I understand that this is just in installation and users having standard library will never face issues.
The suggested change in logic as above will be in the setup.py only i.e. in the installation part in the next release.
So are you in favor of change or not? 

We don't want to make it complicated for all the 99.9% of customers where the HLQ is the same or are having standard libraries. Hence we are adding a condition to accommodate .1% of customer like you who has a different library set i.e. 
```
if (('DB2_INC' not in os.environ)):
#Normal Customer having standard libraries
	dataset_include = "//'%s.SDSNC.H'" % ibm_db_home 
else:
#few exceptional Customers having non-standard libraries
	dataset_include = "//'%s'" % os.environ['DB2_INC']
```
and if this is done for one library it needs to be done fo another one as well.
Am I right?

**Comment by AWADHAMBIKA** [comment]
> @AWADHAMBIKA We should handle this dataset also same like others, so that there will not be any hardcoding in setup.py file and whatever is required can be passed through environment file.
> The mentioned datasets will always be in same HLQ but every organization will have the different HLQ and this is already handled with the variable IBM_DB_HOME which makes the complete dataset name.
> Ex.- $IBM_DB_HOME.SDSNEXIT
> Also, organization can have the different name for the last qualifier, that is what we want to handle through environment file.

Got it. Let me check and get back to you.

**Comment by kparihar7** [comment]
> @kparihar7 Sorry I couldn't quite get your point.
> I understand that this is just in installation and users having standard library will never face issues.
> The suggested change in logic as above will be in the setup.py only i.e. in the installation part in the next release.
> So are you in favor of change or not?
> 
> We don't want to make it complicated for all the 99.9% of customers where the HLQ is the same or are having standard libraries. Hence we are adding a condition to accommodate .1% of customer like you who has a different library set i.e.
> 
> ```
> if (('DB2_INC' not in os.environ)):
> #Normal Customer having standard libraries
> 	dataset_include = "//'%s.SDSNC.H'" % ibm_db_home 
> else:
> #few exceptional Customers having non-standard libraries
> 	dataset_include = "//'%s'" % os.environ['DB2_INC']
> ```
> 
> and if this is done for one library it needs to be done fo another one as well.
> Am I right?

I  am okay for this change but along with this then we need to update its install.md file also and can specify whoever has standard library name, DB2_INC variable is not required for them. Others need to provide this variable.
Agreed?

**Comment by jthyssenrocket** [comment]
@kparihar7 

Do you have SDSNMACS and SDSNC.H under different HLQs or renamed SDSNC.H to something different?
I've worked with Db2 for z/OS customers in 20 years and I've never seen that before.

**Comment by kparihar7** [comment]
> @kparihar7
> 
> Do you have SDSNMACS and SDSNC.H under different HLQs or renamed SDSNC.H to something different?
> I've worked with Db2 for z/OS customers in 20 years and I've never seen that before.

@jthyssenrocket I have all these datasets under same HLQ but SDSNC.H is renamed to DSNC.H.

**Comment by jthyssenrocket** [comment]
Thanks, I've never seen that done before.

**Comment by AWADHAMBIKA** [comment]
So, the new code to handle above discussion will be:
```
if 'zos' == sys.platform:
	sdsnc_h = os.environ['DB2_INC']
	sdsn_macs = os.environ['DB2_MACS']
	if (('DB2_INC' not in os.environ)):
	    dataset_include = "//'%s.SDSNC.H'" % ibm_db_home
	else:
	    dataset_include = "//'%s'" % sdsnc_h
    include_dir = 'sdsnc.h'
    library = []
    library_x = "libdsnao64c.x"
    library_so = "libdsnao64c.so" # fake, but helpful for gen_lib_options in cpython/Lib/distutils/ccompiler.py
    ibm_db_lib = '.'
    if not os.path.isfile(library_x):
		if (('DB2_MACS' not in os.environ)):
	        subprocess.run(['tso', "oput '{}.SDSNMACS(DSNAO64C)' '{}'".format(ibm_db_home, os.path.join(os.getcwd(), library_x))])
	    else:
	        subprocess.run(['tso', "oput '{}(DSNAO64C)' '{}'".format(sdsn_macs, os.path.join(os.getcwd(), library_x))])
    if not os.path.isdir(include_dir):
        os.mkdir(include_dir)
        subprocess.run(['cp', dataset_include, include_dir])
        for f in glob.glob(os.path.join(include_dir, '*')):
            subprocess.run(['chtag', '-tc', '1047', f])
            os.rename(f, '{}.h'.format(f))
    if not os.path.isfile(library_so):
        with open(library_so, "wb") as x_out:
            pass
else:
    library = ['db2']
```
agreed?

**Comment by kparihar7** [comment]
> So, the new code to handle above discussion will be:
> 
> ```
> if 'zos' == sys.platform:
> 	sdsnc_h = os.environ['DB2_INC']
> 	sdsn_macs = os.environ['DB2_MACS']
> 	if (('DB2_INC' not in os.environ)):
> 	    dataset_include = "//'%s.SDSNC.H'" % ibm_db_home
> 	else:
> 	    dataset_include = "//'%s'" % sdsnc_h
>     include_dir = 'sdsnc.h'
>     library = []
>     library_x = "libdsnao64c.x"
>     library_so = "libdsnao64c.so" # fake, but helpful for gen_lib_options in cpython/Lib/distutils/ccompiler.py
>     ibm_db_lib = '.'
>     if not os.path.isfile(library_x):
> 		if (('DB2_MACS' not in os.environ)):
> 	        subprocess.run(['tso', "oput '{}.SDSNMACS(DSNAO64C)' '{}'".format(ibm_db_home, os.path.join(os.getcwd(), library_x))])
> 	    else:
> 	        subprocess.run(['tso', "oput '{}(DSNAO64C)' '{}'".format(sdsn_macs, os.path.join(os.getcwd(), library_x))])
>     if not os.path.isdir(include_dir):
>         os.mkdir(include_dir)
>         subprocess.run(['cp', dataset_include, include_dir])
>         for f in glob.glob(os.path.join(include_dir, '*')):
>             subprocess.run(['chtag', '-tc', '1047', f])
>             os.rename(f, '{}.h'.format(f))
>     if not os.path.isfile(library_so):
>         with open(library_so, "wb") as x_out:
>             pass
> else:
>     library = ['db2']
> ```
> 
> agreed? And the corresponding new variables i.e. DB2_INC & DB2_MACS will be updated in _install.md_ with comments.

@AWADHAMBIKA 
I think DB2_INC and DB2_MACS variable assignment should come under ELSE condition.
Something like this -
```
	if (('DB2_INC' not in os.environ)):
	    dataset_include = "//'%s.SDSNC.H'" % ibm_db_home
	else:
	    sdsnc_h = os.environ['DB2_INC']
	    dataset_include = "//'%s'" % sdsnc_h
```

```
		if (('DB2_MACS' not in os.environ)):
	        subprocess.run(['tso', "oput '{}.SDSNMACS(DSNAO64C)' '{}'".format(ibm_db_home, os.path.join(os.getcwd(), library_x))])
	    else:
		    sdsn_macs = os.environ['DB2_MACS']
	        subprocess.run(['tso', "oput '{}(DSNAO64C)' '{}'".format(sdsn_macs, os.path.join(os.getcwd(), library_x))])
```

**Comment by AWADHAMBIKA** [comment]
sure..

**Pull request merged**
