### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LogicLuminaryy**
Certainly! Here's a stronger description for your pull request:

🚀 Enhancement: Support IBM DB for M1 Macs

Description:
Numerous developers are encountering difficulties with IBM DB not functioning on M1 Macs, even after installing the x86 version of Python. This PR aims to resolve this issue and provide comprehensive support for IBM DB on M1 Mac systems.

Proposed Solution:
I have introduced a series of steps that developers can follow to seamlessly configure and run IBM DB on their M1 Macs. By implementing these steps, users will be able to effectively utilize IBM DB in their development environment without encountering compatibility issues.

Key Changes:

Added detailed instructions for configuring IBM DB on M1 Macs.
Addressed compatibility concerns to ensure smooth integration with the system architecture.
Tested and verified the proposed solution on M1 Macs to ensure reliability and effectiveness.
Benefits:

Enables developers to seamlessly utilize IBM DB on M1 Mac systems.
Enhances the development experience by eliminating compatibility issues.
Improves productivity and efficiency for developers working on M1 Mac platforms.
Instructions for Reviewers:
Please review the provided steps and ensure they are clear, concise, and effective in addressing the IBM DB compatibility issue on M1 Macs. Any feedback or suggestions for further improvements are highly appreciated.

Let's collaborate to streamline IBM DB support for M1 Macs and enhance the development experience for all users.

Thank you for your attention and assistance in addressing this critical issue!

### CODE REVIEW

**Comment by bimalkjha** [comment]
@LogicLuminaryy Please check https://github.com/ibmdb/python-ibmdb/pull/917/checks?check_run_id=22286568670 and complete DCO signoff. Thanks.

**Comment by bimalkjha** [comment]
@LogicLuminaryy Have you checked this info in README.md file about M1 Chip system: https://github.com/ibmdb/python-ibmdb/tree/master?tab=readme-ov-file#for-macos-m1m2-apple-silicon-chip-system ?

Also, detailed installation steps are documented here: https://github.com/ibmdb/python-ibmdb/blob/master/INSTALL.md#-7-ibm_db-installation-on-macos-m1m2-chip-system-arm64-architecture
You may like to add your instructions here. Thanks.

**Comment by LogicLuminaryy** [comment]
@bimalkjha @LogicLuminaryy, could you please inform me of any action items? I haven't come across the solution provided above anywhere else hence wanted your people suggestion what is best way. 
Implementing the suggested approach could assist individuals encountering issues while installing Ibm_db.

**Comment by LogicLuminaryy** [comment]
https://github.com/ibmdb/python-ibmdb/pull/921 I have raised PR

**Comment by LogicLuminaryy** [comment]
@bimalkjha shall i close this PR?

**Comment by bimalkjha** [comment]
@LogicLuminaryy Please add DCO signoff. Thanks.

**Comment by LogicLuminaryy** [comment]
I have done as per request,Please let me know if anything needed - thanks @bimalkjha

**Pull request closed without merging**
