### PR TITLE
Honor GCC environment variables

### PR DESCRIPTION
**Pull request by kincerb**
In our python runtime we use the `CFLAGS` and `LDFLAGS` environment variables to locate the header files and libraries needed for compiling wheels.

In the current setup.py file, it does not take these into account and causes our compilation to fail.

I have tested this modification to properly test if the headers/libraries are found to continue installation. Everything works as expected.

Please accept this PR or educate me on how best to accomplish this on an environment where the headers/libraries are in different locations from when the runtime was originally compiled.

Thank you!

### CODE REVIEW

**Comment by bimalkjha** [comment]
@kincerb Most of the code changes are to convert single quote to double quote. Could you please explain why this conversion is required? Otherwise, please reverse all unwanted changes.
 Also, we would like to know the error that you are getting when you do not set CFLAGS and LDFLAGS and trying to install ibm_db. Before installation, do you set IBM_DB_HOME or not? We would like to see the compilation error and steps to reproduce it. Thanks.

**Comment by bimalkjha** [comment]
@kincerb Any update on it? Please resolve the conflict and undo ' to " changes. Thanks.

**Comment by kincerb** [comment]
@bimalkjha Sorry about the delayed response. My auto-formatter converted all the quotes and I didn't catch that. I will undo those changes as they are obviously not needed and just cause visual noise.

I will see if I can get some error output. To my knowledge, `IBM_DB_HOME` is not being set.

Myself and my team maintain python runtimes that are bundled as AppImages for other teams in our company. One of those teams were the ones using this package.

I recall the error was being thrown specifically from the `setup.py` file because it was trying to do some pre-checks for C headers... and because our runtime relies upon honoring the CFLAGS and LDFLAGS so these can be properly found, the current version of your `setup.py` doesn't work for this team.

I verified the changes I made (minus the superfluous formatting) allow the team to install and use your package as expected.

I will see if I can get actual output from the error. I figured either way, you would want to honor the standard environment variables for GCC.

**Comment by bimalkjha** [comment]
Pushed the changes with latest commit. Thanks.

**Pull request closed without merging**
