### PR TITLE
Fix whitespace issues

### PR DESCRIPTION
**Pull request by kadler**
- Use 4-spaces instead of tabs to comply with PEP-8

- Use Unix line endings. Users on Windows should set core.autocrlf:
  https://help.github.com/articles/dealing-with-line-endings/#platform-windows

### CODE REVIEW

**Comment by kadler** [comment]
I realize this creates a massive amount of noisy churn, but the code is a mess of tabs and spaces (especially the C code) so it's better to get this fixed sooner rather than later.

**Comment by SabaKauser** [comment]
Hi Kevin,
Do I need to validate the changes, install and test or I can merge them directly and forget?

**Comment by kadler** [comment]
It's just whitespace changes except for moving the comments for the structure initializers to the other side. You can see the diff with whitespace ignored here: https://github.com/ibmdb/python-ibmdb/pull/315/commits/27f59e2966737d8e4f0857378a26dc6f7b7c96a6?w=1

**Comment by kadler** [comment]
So, I ignorantly opened this PR from my master branch instead of a topic branch. I'm going to re-open this PR from a topic branch instead so that I can keep my master branch in sync.

**Pull request closed without merging**
