### PR TITLE
Add Trove classifiers for supported Python versions.

### PR DESCRIPTION
**Pull request by jezdez**
This helps tools like @brettcannon's [caniusepython3](https://pypi.org/project/caniusepython3/) and generally signals better the supported version on PyPI.

### CODE REVIEW

**Comment by SabaKauser** [comment]
Can you sign-off:
DCO 1.1 Signed-off-by: Random J Developer <random@developer.org>

**Comment by jezdez** [comment]
@SabaKauser Done.

**Comment by SabaKauser** [comment]
> 
> 
> @SabaKauser Done.

@Jannis, I thought you would sign-off by adding your full name and email id.

**Comment by jezdez** [comment]
> > @SabaKauser Done.
> 
> @Jannis, I thought you would sign-off by adding your full name and email id.

I'm sorry, I assumed you meant to add this to the commits message, like I did in https://github.com/ibmdb/python-ibmdb/pull/395/commits/da9809de77711df3de26794247b9567c7d062065.

**Comment by jezdez** [comment]
DCO 1.1 Signed-off-by: Jannis Leidel <jannis@leidel.info>

**Comment by SabaKauser** [comment]
> 
> 
> > > @SabaKauser Done.
> > 
> > 
> > @Jannis, I thought you would sign-off by adding your full name and email id.
> 
> I'm sorry, I assumed you meant to add this to the commit's message, like I did in [da9809d](https://github.com/ibmdb/python-ibmdb/commit/da9809de77711df3de26794247b9567c7d062065).

Thanks, Done! :)

**Pull request merged**
