### PR TITLE
Fix whitespace issues

### PR DESCRIPTION
**Pull request by kadler**
This PR replaces #315, since that one was pulled from my master branch by mistake.

In this PR, various whitespace cleanups are performed:
- [x] Replaces tabs with 4 spaces
- [x] Converts from CRLF to LF line-endings
- [x] Removes trailing blanks
- [x] Adjusts indentation to be consistently 4 spaces to comply with PEP 8

### CODE REVIEW

**Comment by SabaKauser** [comment]
@kadler ,
I am working on making new release. Should this be merged?

**Comment by kadler** [comment]
I was trying to get it in before the release, but I ran in to problems with #373. I will try to get this completed in the next day or so, but I'm not sure it should hold up the release.

**Comment by kadler** [comment]
@SabaKauser FYI, this is ready to go

**Comment by kadler** [comment]
I rebased on top of #382 and it should be ready to go again.

Again, it's pretty much just whitespace fixes - best to ignore whitespaces differences when looking at the changes: https://github.com/ibmdb/python-ibmdb/pull/344/files?utf8=%E2%9C%93&diff=unified&w=1

**Pull request merged**
