### PR TITLE
 Allow null values in parameters array, since DB2 allows them

### PR DESCRIPTION
**Pull request by sasa-tomic**
These checks were breaking SQLAlchemy, when adding multiple objects to a session and flushing them together

### CODE REVIEW

**Comment by SabaKauser** [comment]
Hello,
Could you please share the usecase for which you have fixed .

**Comment by sasa-tomic** [comment]
I'm not able to share the original example, but I can outline the scenario which wasn't working.

Something along the lines of https://stackoverflow.com/questions/34664700/how-to-add-all-elements-from-python-dictionary-to-database should be similar to the requirement we had:

```
from sqlalchemy import Column, String, Integer, create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Person(Base):
    __tablename__ = 'person'
    id = Column(Integer, primary_key=True)
    name = Column(String(250), nullable=True)
    job = Column(String(250), nullable=True)

engine = create_engine('sqlite:///persons.sqlite')
Base.metadata.create_all(engine)

session = sessionmaker(bind=engine)
s = session()

s.add_all([
  Person(name='John', job='developer'),
  Person(name='Marry'),
  Person(name='Jack', job='manager'),
])

s.commit()
```
we had a lot more columns, and used reflection on DB2WoC, but that shouldn't affect this PR.

**Comment by sasa-tomic** [comment]
I resolved the conflict with master

**Comment by amukherjee28** [comment]
@sasa-tomic 

I working on this PR.

Need some explanation on the above PR.

I am running the following sample code 
```
from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer, String, MetaData, inspect, ForeignKey
from sqlalchemy.sql.expression import column, null
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class demo1(Base):
    __tablename__ = 'testTable1'
    id = Column(Integer,primary_key=True)
    name = Column(String(50), nullable=True)
    Address = Column(String(50), nullable=True)

engine = create_engine('ibm_db_sa://user:passwd@hostname:portnumber/database',echo = True)

print("=> ENGINE\n")
print(engine)

print("=> Creating Table demoTab1\n")
inspector = inspect(engine)
if ('testTable1' in inspector.get_table_names()):
    engine.execute("DROP TABLE \"testTable1\"")
Base.metadata.create_all(engine)

session = sessionmaker(bind=engine)
ses = session()

ses.add_all([
    demo1(id=1,name='Arnab',Address='Kolkata-94'),
    demo1(id=2)
])

ses.commit()
```

 When I run this code, I have the following output as of now

```
=> ENGINE

Engine(ibm_db_sa://user:***@hostname:port/database)
=> Creating Table demoTab1

/work/amukherjee/PYTHON_IBM_DB/PYTHON_DEBUG_BUILDS/python_310/python310/lib/python3.10/site-packages/ibm_db_sa/reflection.py:210: SAWarning: Dialect ibm_db_sa:ibm_db_sa will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  return [self.normalize_name(r[0]) for r in connection.execute(query)]
2022-01-04 04:37:31,752 INFO sqlalchemy.engine.Engine SELECT "SYSCAT"."TABLES"."TABNAME"
FROM "SYSCAT"."TABLES"
WHERE "SYSCAT"."TABLES"."TYPE" = ? AND "SYSCAT"."TABLES"."TABSCHEMA" = ? ORDER BY "SYSCAT"."TABLES"."TABNAME"
2022-01-04 04:37:31,752 INFO sqlalchemy.engine.Engine [dialect ibm_db_sa+ibm_db_sa does not support caching 0.00029s] (b'T', b'NEWTON')
2022-01-04 04:37:31,755 INFO sqlalchemy.engine.Engine DROP TABLE "testTable1"
2022-01-04 04:37:31,756 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-01-04 04:37:31,771 INFO sqlalchemy.engine.Engine COMMIT
2022-01-04 04:37:31,786 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-01-04 04:37:31,787 INFO sqlalchemy.engine.Engine SELECT "SYSCAT"."TABLES"."TABNAME"
FROM "SYSCAT"."TABLES"
WHERE "SYSCAT"."TABLES"."TABSCHEMA" = ? AND "SYSCAT"."TABLES"."TABNAME" = ?
2022-01-04 04:37:31,787 INFO sqlalchemy.engine.Engine [dialect ibm_db_sa+ibm_db_sa does not support caching 0.00021s] (b'NEWTON', b'testTable1')
2022-01-04 04:37:31,789 INFO sqlalchemy.engine.Engine
CREATE TABLE "testTable1" (
        id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
        name VARCHAR(50),
        "Address" VARCHAR(50),
        PRIMARY KEY (id)
)


2022-01-04 04:37:31,789 INFO sqlalchemy.engine.Engine [no key 0.00012s] ()
2022-01-04 04:37:32,050 INFO sqlalchemy.engine.Engine COMMIT
2022-01-04 04:37:32,061 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-01-04 04:37:32,064 INFO sqlalchemy.engine.Engine INSERT INTO "testTable1" (id, name, "Address") VALUES (?, ?, ?)
2022-01-04 04:37:32,064 INFO sqlalchemy.engine.Engine [dialect ibm_db_sa+ibm_db_sa does not support caching 0.00048s] ((1, 'Arnab', 'Kolkata-94'), (2, None, None))
2022-01-04 04:37:32,069 INFO sqlalchemy.engine.Engine COMMIT
```

So in the second row where no values were passed I see it is None is taken by default.

Could you please explain once what the PR is addressing in this case.

I took the sample code based on the previous PR raised.

**Comment by amukherjee28** [comment]
Part of PR #689

**Pull request closed without merging**
